ToFuProject/datastock

datastock/_DataCollection_comp.py
datastock/_class1.py
datastock/_class2.py
datastock/_class2_interactivity.py
datastock/_class3.py
datastock/_direct_calls.py
datastock/_generic_check.py
datastock/_generic_utils.py
datastock/_plot_BvsA_as_distribution.py
datastock/_plot_as_array.py

Main changes:
* plot_BvsA_as_distribution() is implemented for 1d arrays of the same shape
* plot 2 samples against each other as a scatter plot
* all black (default)
* also allows to color according to any data of same shape
* also allows to color according to a color dict setting bounds on other data of the same shape
* also plots as a 2d distribution
* Also prints values of all other data of the same shape for selected samples
* Interactivity is better handled:
* better handling of toolbar buttons (please use the second toolbar): zooming, dragging, home
* resizing events are better handled
Examples:
--------------
```
In [2]: nt0 = 10000; t0 = np.linspace(0, 10, nt0); nt1 = 80; t1 = np.linspace(0, 10, nt1); x0 = t0%2 + …
```

Add plot_BvsA_as_distribution() for 1d arrays

---

datastock/_class2.py
datastock/_class3.py
datastock/_generic_check.py
datastock/_plot_BvsA_as_distribution.py

Main changes:
* method plot_BvsA_as_distribution() now works for 2d arrays, and the profile is chosen with keyX/axis can be plotted:
* keyX = None: index (axis = 1 by default)
*  keyX = ref: index (axis set by ref)
* keyX = 1d data (axis set by data)
* keyX = 2d data (axis = 1 by default)
Known issue:
---------------
* The zoom / pan / home buttons on the toolbar seem to work properly / not work properly depending on the version of matplotlib that is installed. Some deprecation warnings may appear depending on that too (to be fixed later).
Issues:
-------
* Fixes issue #3 in devel
Examples:
-----------
```
In [2]: nt = 1000; t = np.linspace(0, 10, nt); nrho = 100; rho = 0.1*np.cos(t)[:, None] + np.linspace(-1, 1, nrho)[None, :]; Te0 = 1 - …
```

[#003] plot_BvsA_as_distribution() working for 2d arrays

---

datastock/_class1_compute.py
datastock/_plot_correlations.py

[#012] coompute_correlations() more robust + plot more readable

---

datastock/_class1.py
datastock/_class1_check.py
datastock/_class2.py
datastock/_class2_interactivity.py
datastock/_plot_BvsA_as_distribution.py
datastock/_plot_as_array.py
datastock/_plot_correlations.py
datastock/_plot_text.py

Main changes:
* `dstatic` removed (no added-value compared to `dobj`)
* `__dlinks` implemented, as well as `show_links()`
* More robust `_class_checks.py` on params
* `setup_interactivity()` debugged and cleaner (partly moved to `_class2_interactivity.py`)
* `yticklabels` on right hand side for `plot_correlations()`
* connect now does `setup_interactivity()` + `disconnect_old()` + `connect()`
* Parameters harmonization is now optional
* xlim and ylim are more robust in `plot_as_array()`

Issue015 simplify

---

datastock/_class1.py
datastock/_class1_check.py
datastock/_class1_compute.py
datastock/_class1_interpolate.py
datastock/version.py

Main changes:
* Implemented DataStock.interpolate(), operational to interpolate on 1d and 2d data
* Can take 1 or 2 monotonous data as coordinate
* Can take a list of 1d or 2d data to interpolate on 
* Can interpolate in linear-linear or log-log scale
* Takes pts to interpolate at, that can be any shape (grid or not) as long as each dimenion is provided separately
* Uses B-splines for interpolation (deg to be chosen) and returns nans for out-of-bounds values
* Returns a dict of arrays, and optionally a dict of input parameters
Examples:
-------------
```
In [8]: nt0 = 20; t0 = np.linspace(1, 10, nt0); nx = 30; x = np.linspace(1, 10, nx); ny=100; y = np.linspace(0, 10, ny); x0 = 10 + np.sin(t0)[:, None] * (x-x.mean())[None, :]; y0 = x0[:, :, None]*y[None, No
...: ne, …
```

Issue019 interpolation

---

datastock/_plot_BvsA_as_distribution.py
datastock/_plot_as_array.py
datastock/_plot_correlations.py

Main changes: (minor debugging)
* connect=False automatically returns dax and dgroup
* Clic on axes for plot_as_array() works if keyZ != None (3d arrays)
* Clic on axes for plot_as_array() works if keyX != None (1d arrays)

Issue024 debug plot as array

---

datastock/_class2.py

Main changes:
* More robust (try / except)
* Better error message

[#34] More robust + better error message

---

datastock/_class1.py
datastock/_class1_check.py
datastock/_plot_as_array.py

Minor changes
Fixes, in devel, issue #39

Issue038 debug plasma2d

---

datastock/_class1_check.py
datastock/_class1_uniformize.py

Main changes:
* `get_ref_vector()` automatically reckognizes when a value vector is passed that matches a known vector
* Minor bug fixes in `_class1_check._check_conflicts()`

Issue48 ref vector reckognition

---

datastock/_generic_check.py

Main changes:
* `_generic_check._check_flat1darray()`: typo corrected on sign + sign can now be a list of standard expressions
* `_generic_check._check_var()`: sign can now be a list of standard expressions

Issue54 checks: 

---

datastock/_generic_check.py

Main changes:
* Replaced `[k0]` by `get(k0)`
* `ds._generic_check._check_flat1darray(unique=True)` implemented

[#65] More robust dict check + added unique to flat1d_array

---

.github/workflows/python-publish.yml
datastock/_class1.py
datastock/_class1_check.py
datastock/_class1_uniformize.py
datastock/_generic_check.py

Main changes:
* `ddefparams` is now checked in more details before use
Issues:
-------
* Fixes, in devel, issue #65

[#69] ddefparams is now fully checked

---

datastock/_class1.py
datastock/_class1_binning.py
datastock/_class1_domain.py
datastock/_class1_interpolate.py
datastock/tests/test_01_DataStock.py

Main changes:
* `binning(key=str, ref_key=str, bins=array or str)` implemented
* `interpolate()` and `binning()` share more common subroutines
* `get_domain_ref()` implemented
* `interpolate(domain=dict) `implemented
* Unit tests updated accordingly

Issue071 binning

---

datastock/_class1.py
datastock/_class1_binning.py
datastock/_class1_check.py
datastock/_class1_compute.py
datastock/_class1_interpolate.py
datastock/_generic_check.py
datastock/tests/test_01_DataStock.py

Main changes:
* Minor clean-up
* Debugged setting `ref` automatically if not specified
* Debugged `binning`
* `interpolate(store=bool, inplace=bool)` implemented

Issue077 minor cleanup + store interpolations

---

datastock/_class1.py
datastock/_class1_interpolate.py
datastock/_class1_uniformize.py
datastock/_generic_check.py
datastock/_plot_as_array.py

Issues:
----------
* Fixes, in devel, issue #83

Issue083 plot sameref

---

datastock/_class1_domain.py
datastock/_class1_interpolate.py
datastock/_class2.py
datastock/_class2_interactivity.py
datastock/_generic_check.py
datastock/_plot_as_array.py

Main changes:
* Minor debugging or robustness improvements

[#89] More robust check_dax vs None type

---

datastock/_class1_domain.py
datastock/_class1_interpolate.py
datastock/_class1_uniformize.py

Main changes:
* `get_ref_vector(key=str)` debugged 
* `interpolate(domain=float)` uses nearest-neghbour

Issue092 getrefvector

---

datastock/_generic_utils.py
datastock/_saveload.py

Main changes:
* `ds.load()` generalized to rebuild from any subclass of `DataStock` (such as tofu `Collection`)
* Also handles better `float` / `int` of numpy vs python
* And typing of variables by `save()` now appends `__type` instead of `_type` to be more robust against user-defined variables.

Issue100 saveload

---

datastock/_class1.py
datastock/_class1_binning.py
datastock/_class1_interpolate.py
datastock/_class1_uniformize.py

Main changes:
-`datastock/_class1_uniformize.get_ref_vector_common(strategy=str)` implemented to allow the user to force-pick the desired time vector, and propagated 
Issues:
-----------
* Fixes, in devel, issue #95

[#95] Modifying val line to take directly input time values

---

datastock/__init__.py
datastock/_class1_binning.py
datastock/_generic_check.py

Main changes:
* Faster multi-dimensional binning
Issues:
----------
Fixes, in devel, issue #104

Issue103 new binning

---

datastock/_plot_as_array.py

Main changes:
* More robust plot_as_array()
Issues:
--------
Fixes, in devel, issue #109

[#109] plot_as_array() more robust vs Nan or Inf limits

---

datastock/_class1_interpolate.py
datastock/version.py

Main changes:
* Plotting is now more robust, with better error messages: 
- #110 
- #112

Preparing 0.0.31

---

.github/workflows/python-testing-matrix.yml
datastock/_class1_check.py

Main changes:
----------------------
* replaced `isinstance(aa, np.int)` by `isinstance(aa, np.integer)`
* replaced `isisntance(aa, np.float)` by `isisntance(aa, float)`
* replaced `[aa].dtype == np.int` by `[aa].dtype == int`
Issues:
---------
Fixes, in devel, issue #114

[#114] Fixed all np.int and np.float

---

.github/workflows/python-testing-matrix.yml
datastock/_class1_check.py
datastock/_class1_interpolate.py
datastock/_class3.py
datastock/_plot_BvsA_as_distribution.py
datastock/_plot_as_array.py
datastock/_plot_as_mobile_lines.py
datastock/_plot_as_profile1d.py
datastock/version.py

Main changes:
* fixed issue with numpy types
* MacOS supported again
* more robust plotting + show_commands implemented

Prepare 0.0.32

---

datastock/_saveload.py

Main changes:
* Implemented new simpler and more powerful version of `get_files()`:
```
get_files(
dpfe=str, list, dict,
returnas=list or dict,
strict=bool
)
```

[#121] First operation upgrade, now simpler call for the routine

---

datastock/_saveload.py
datastock/version.py

Main changes:
Better `get_files()` #122

Prepare 0.0.33

---

datastock/_class1_binning.py

Main changes:
* binning(statistic='sum_snooth') implemented for most typical use cases
* Preserves total flux
Issues:
--------
Fixes, in devel, issue #124

binning(statistic='sum_snooth')

---

datastock/__init__.py
datastock/_generic_utils_plot.py

Main changes:
* set_aspect3d() implemented and operational
Issues:
-------
Fixes, in devel, issue #129

set_aspect3d()

---

datastock/_class1.py
datastock/_class1_domain.py
datastock/_class1_interpolate.py
datastock/_class1_uniformize.py

Main changes:
* `get_ref_vector(key=str)` implemented to disambiguate
Issues:
--------
Fixes, in devel, issue #132

[#132] get_ref_vector(key=str) implemented to disambiguate

---

datastock/_saveload.py

Main changes:
* `load()` now properly handles `chararray` type
Issues:
--------
Fixes, in devel, issue #136

[#136] Fixed

---

datastock/_class1.py
datastock/_class1_compute.py
datastock/_plot_as_array.py

Main changes:
* `extract(inplace=bool)` reactivated
* `plot_as_array(inplace=bool)` reactivated
Issues:
--------
Fixes, in devel, issue #142

extract(inplace=bool) reactivated

---

datastock/_class1_check.py

Main changes:
------------------
* `remove_obj()` does not crash anymore when obj is already empty
Issues:
--------
Fixes, in devel, issue #146

[#146] Fixed

---

datastock/_class1_check.py

Main changes:
* `remove_obj()` now more robust vs empty objects or objects not in `dobj`
* `add_obj()` now more robust vs pre-existing identical objects
Issues:
-------
Fixes, in devel, isseu #148

Issue148 pre existing object

---

datastock/_class1_check.py

Main changes:
* `add_data(ref=list)` works (only tuples were allowed before)
Issues:
-------
Fixes, in devel, issue #157

`add_data(ref=list)` works

---

.github/workflows/python-testing-matrix.yml

Main changes:
Added python 3.11 to unit tests matrix
Issues:
-------
Fixes, in devel, issue #172

Issue172 python 311

---

datastock/_class0.py
datastock/_class1.py
datastock/_saveload.py
datastock/tests/test_01_DataStock.py
datastock/version.py

Main changes:
* `load(coll=...)` implemented #185

Prepare 0.0.44

---

datastock/_class1_domain.py
datastock/_class1_interpolate.py

Main changes:
* `interpolate(domain=dict)` now accepts input by reference and index (even with no identified `ref_vector`)
Issues:
-------
Fixes, in devel, issue #188

Issue188 domain ind

---

datastock/_class1_interpolate.py

Main changes:
* `interpolate(domain=None, x0=scalar)` now works
Issues:
--------
Fixes, in devel, issue #192

[#192] `interpolate(domain=None, x0=scalar)` now works

---

datastock/_class2.py

Follow-up on #208, merged too fast

[#207] minor debug

---

datastock/_generic_check.py

Main changes:
* `_generic_check._check_vectbasis(direct=bool)` implemented
Issues:
--------
Fixes, in devel, issue #218

[#218] `_check_vectbasis(direct=bool)` implemented

---

datastock/_class0.py
datastock/_saveload.py

Main changes:
* `load()` more robust vs names
Issues:
-------
Fixes, in devel, issue #232

[#232] More robust loading
