ToFuProject/datastock

datastock/_class3.py, datastock/_plot_BvsA_as_distribution.py
Main changes:
`plot_BvsA_as_distribution() `now allows to set:
* `dist_rel = True / False`: if True the 2d distribution is plotted as a real distribution function (normalized to its integral)
* `dist_ample_min = int` (set to 1 by default), lower limit for which a distribution element can be considered valid, any lower value will be set to nan.
Examples:
--------------
```
In [1]: nt0 = 1000; t0 = np.linspace(0, 10, nt0); nx = 100; x = np.linspace(0, 10, nx); x0 = np.sin(t0)[:, None] * np.exp(-(x-x.mean())**2/ 0.1)[None, :]; y0 = x0 + np.random.normal(scale=0.1, size=(nt0, n
...: x));
In [2]: st = ds.DataStock(); st.add_ref(key='t0', size=nt0); st.add_ref(key='x', size=nx); st.add_data(key='t0', data=t0); st.add_data(key='x0', data=x0); st.add_data(key='y0', data=y0); …
```
=> [#003] plot_BvsA_as_distribution(dist_rel=bool dist_sample_min=int)

datastock/_DataCollection_comp.py, datastock/_class1_check.py, datastock/_class2.py, datastock/_class2_interactivity.py, datastock/_class3.py, datastock/_direct_calls.py, datastock/_plot_as_array.py
Main changes:
* `plot_BvsA_as_distribution()` is operational for 1d and 2d arrays
* plot_as_array():
* now operational for 1d, 2d and 3d arrays
* can now take keyX, keyY, keyZ arguments (they have to be monotonic uniform 1d data vectors)
* can handle text arrays for keyX and keyY for 2d arrays (but interactivity to be fixed)
* Better interactivity
Issues:
-------
* Fixes, in devel, issue #5 
* Fixes, in devel, issue #2 
Examples:
-----------
Preparation of the class containing all data
```
In [2]: nt = 100; t = np.linspace(0, 10, nt); nrho = 80; rho0 = np.linspace(-1, 1, nrho); rho = 0.1*np.cos(t)[:, None] + np.linspace(-1, 1, nrho)[None, :]; Te0 = 1 - rho**2; Te1 = Te0 + np.random.normal(scale
...: =0.1, size=(nt, nrho));
In [3]: nx = 50; …
```
=> Issue003 plot BvsA as distribution

datastock/_class1_check.py, datastock/_class2.py, datastock/_class2_interactivity.py, datastock/_plot_BvsA_as_distribution.py, datastock/_plot_BvsA_as_distribution_check.py, datastock/_plot_as_array.py
Main changes:
* Better handling of bool and sparse arrays for interactivity
Issues:
----------
* Fixes, in devel, issues #26 #27 
Examples:
--------------
```
In [2]: import scipy.sparse as scpsparse
In [3]: nt0 = 20; t0 = np.linspace(1, 10, nt0); nx = 30; x = np.linspace(1, 10, nx); ny=100; y = np.linspace(0, 10, ny); x0 = 10 + np.sin(t0)[:, None] * (x-x.mean())[None, :]; y0 = x0[:, :, None]*y[None, No
...: ne, :] + np.random.normal(scale=0.1, size=(nt0, nx, ny)); tlab0 = [f't = {round(tt)}' for tt in t0]; tlab1 = [f'{round((tt-5)**2)}' for tt in x]; x1 = x0 + np.random.normal(scale=0.1, size=x0.shape)
...: ; x2 = x0 + np.random.normal(scale=0.01, size=x0.shape);
In [4]: st = ds.DataStock(); st.add_ref(key='nt', size=nt0); …
```
=> Issue026 plot bool

datastock/_class1_compute.py, datastock/_class2.py, datastock/_class2_interactivity.py, datastock/_class3.py, datastock/_plot_BvsA_as_distribution.py, datastock/_plot_as_array.py, datastock/_plot_as_profile1d.py, datastock/tests/test_01_DataStock.py
Main changes:
* More robust and cleaner code for interactvity
* plot_as_profile1d(key=..., key_time=..., keyX=..., bck=...) implemented with:
* key any 2d data
* key_time: any 1d data sharing a ref with key (does not have to be monotnic)
* keyX: any 1d or 2d data with either, the other ref, or the same refs as key
* bck: False, 'lines' or 'envelop'
Examples:
--------------
```
In [2]: nt0 = 20; t0 = np.linspace(1, 10, nt0); nx = 30; x = np.linspace(1, 10, nx); ny=100; y = np.linspace(0, 10, ny); x0 = 10 + np.sin(t0)[:, None] * (x-x.mean())[None, :]; y0 = x0[:, :, None]*y[None, None, :] + np.random.normal(scale=0.1, size=(nt0, nx, ny));
...: tlab0 = [f't = {round(tt)}' for tt in t0]; tlab1 = [f'{round((tt-5)**2)}' for tt in x]; x1 = x0 + …
```
=> Issue006 plot profile1d

datastock/_class1.py, datastock/_class1_check.py, datastock/_class1_interpolate.py, datastock/tests/test_01_DataStock.py
Main changes:
* `get_ref_vector()` implemented
* `get_ref_vector_common()` implemented
* Default names for ref and data are now shorter: `n` and `d` respectively
Issues:
----------
Fixes, in devel, issue #42 
Examples:
--------------
Shorter names:
```
In [2]: plasma = ds.DataStock();
In [3]: plasma.add_data(key='t', data=np.linspace(0, 10, 11), dim='time')
In [4]: plasma
Out[4]: 
ref key  size  nb. data  nb. data monot.
-------  ----  --------  ---------------
n00      11    1         1              
data key  shape  ref       dim   monot    units  quant  name  source
--------  -----  --------  ----  -------  -----  -----  ----  ------
t         (11,)  ('n00',)  time  (True,)                
```            
ref vectors:
```
In [4]: nt0 = …
```
=> Issue042 monotonous vector per dim

datastock/_class1.py, datastock/_class1_check.py
Attribute `_dshow` allows to define custom fields to be displayed by method `show()` for objects.
Simply provide a dict of key / list pairs, giving the list of attributes to be displayed for each obj category.
Syntax allows to access sub-dict by providing the path using a dot `.` as sub-dict separator.
Example:
------------
```
In [1]: st = ds.DataStock()
In [2]: st.add_obj(which='blabla', key='bla0', att0=1, att1='A', att2={'a': 3, 'b': 4})
In [3]: st
Out[3]: 
blabla  att0  att1
------  ----  ----
bla0    1     A   
In [4]: st._dshow['blabla'] = ['att1', 'att2.b']
In [5]: st
Out[5]: 
blabla  att1  b
------  ----  -
bla0    A     4
```
=> [#50] Implemented _dshow for obj, as class attribute

datastock/_class1.py, datastock/_class1_check.py, datastock/_generic_check.py, datastock/tests/test_01_DataStock.py
Main changes:
* `_generic_check._check_var(sign=...)` implemented to check the sign with a regular expression (any inequality)
* `_generic_check._check_flat1darray(size=..., dtype=..., norm=bool, can_be_None=bool)` implemented 
* `_generic_check._check_dict_valid_keys()` will check the keys of a dict (all, any + dict of key types fed to `_check_var`, `_check_var_iter` or `_check_flat1darray`)
* `_generic_check._obj_key()` implemented to set `None` key to default short (using new `_dshort `class attribute)
* `show(show_which=tuple)` implemented, allowing `show_obj()`
* `_generic_check._check_vectbasis(e0=..., e1=..., e2=..., dim=...)` implemented for 2d and 3d vector basis
* `get_lparam()` now properly handles nested dict
Issues:
----------
* Fixes, in devel, issues …
=> [#54] Better _generci_check routines + show_obj()

datastock/_class1.py, datastock/_class1_check.py, datastock/_generic_utils.py, datastock/_saveload.py, requirements.txt, setup.py
Main changes:
* `astropy` is now a dependency
* `units` are now by default astropy units
* `show()` now uses `'{:.3e}'` for floats and arrays of 3 floats
Issues:
---------
* Fixes, in devel, issues #57 , #60
=> Issue57 astropy units

datastock/_class1_check.py, datastock/_generic_check.py, datastock/_saveload.py
Main changes:
* `_generic_check._check_dax() `pproduces better error message for `dax`, and is more robust (no `type` check)
* `Astropy` units conversion is more robust and uses the `Unit(str)` syntax
Issues:
---------
* Fixes, in devel:
- issue #62 
- issue #63
=> Issue063 dax error msg + 62 better astropy units conversions

datastock/_class0.py, datastock/_class1.py, datastock/_class1_check.py, datastock/_generic_utils.py, datastock/_saveload.py
Main changes:
* `to_dict(asarray=True, with_types=True, type_str=None)` implemented to control asarray in datastock instead of in np.savez()
* `_ddef` attribute now uses a subdict to avoid inhomogenous sequence
Issues:
-------
* Fixes issue #67 in devel
=> Numpy deprecation on ragged arrays

datastock/_class1.py, datastock/_class1_interpolate.py, datastock/tests/test_01_DataStock.py
Main changes:
* `interpolate(ref_com=str)` implemented
* `ref_com` has to be the first or last `ref` of `x0`
* should with `domain` as long as they are not referring to the same `ref`
* unit tests ok for up to 2 dimensional, `domain` not tested
=> Issue073 interpolate common refs

datastock/__init__.py, datastock/_saveload.py
Main changes:
* `ds.get_files()` implemented
```
def get_files(
path=None,
patterns=None,
pfe=None,
dpath=None,
):
""" Return a dict of path keys associated to list of file names
A pfe is a str describing the path, file name and extension
If pfe is provided, it is just checked
If path / patterns is provided, return all files in path matching patterns
If dpath is provided, must be a dict with:
- keys: valid path
- values: dict with 'patterns' or 'pfe'
"""
```
Useful routine to quickly scan:
- `path` / `pattern`: a  single folder looking for files matching (or excluding) a naming pattern
- `dpath`: multiple folder looking for files matching (or excluding) folder-specific naming pattern
Result always returned as a `dict`.
Handles both relative and absolute paths (as input). …
=> [#97] ds.get_files() implemented

datastock/_class1.py, datastock/_class1_binning.py, datastock/_class1_interpolate.py, datastock/_generic_utils.py, datastock/tests/test_01_DataStock.py
Main chnages:
* `binning()` now:
- requires `axis` as input (or default to all dimensions => flattened arrays)
- can handle known keys for `data`, `bin_data` and `bins`
- can handle npndarrays for `data`, `bin_data` and `bins`
- can hande 1d and 2d binning
- can handle binning for any dimensions (flattened along `axis` = list of indices used for binning)
- can handle binning for any dimension of `data` and `bin_data` (flattened)
- can hande binning for  any dimension of `data` (non-flat) provided `bin_data` is not time-varying (flattened)
- can be used for simple binning or for integration (`integrate=True`)
* if `store=True`, all `data`, `bin_data` and `bins` have to be keys to known items
=> Issue105 generalize binning

datastock/_plot_as_array.py
Main changes:
* Better error msg for `plot_as_array()` when choosing `keyX`, `keyY`, `keyZ`...
Issues:
---------
Fixes, in devel, issue #111
=> [#111] Better error msg

datastock/_class1_interpolate.py, datastock/_generic_check.py
Main changes:
* `interpolate(deriv=...)` now takes:
- `deriv = int` for 1d bsplines
- `deriv = [int, int]` for 2d bsplines  
Issues:
-------
Partially fixes, in devel, issue #149
=> Basics for future Deriv2d implementation

datastock/_class2.py, datastock/_class2_interactivity.py
Main changes:
* the following 3 addition dtype options are available for mobile definition:
- `'x'`: calls `text.set_x()`
- `'y'`: calls `text.set_y()`
- `'position'`: calls `text.set_position()`
Issues:
-------
Fixes, in devel, issue #158 
Examples:
-----------
Used for moving spectral labels in
=> text can move

datastock/_class1.py, datastock/_class1_uniformize.py
Main changes:
* `get_ref_vector(warn=True)` now:
- only ignores when no ref vector is found
- multiple vectors will still raise warning
* `get_ref_vector(key_exclude=list, ref_exclude=list)` implemented
- allows to exclude from search vectors or refs that are known to be non-relevant
- makes search more efficient
* `get_ref_vector_common(key_exclude=list, ref_exclude=list)` implemented
- same as above
Issues:
-------
Fixes, in devel, issue #162
=> Issue162 ref vector exclude

datastock/_generic_utils.py, datastock/version.py
Main changes:
(mostly for spectrall saving / loading)
* #166
=> Prepare 0.0.41

datastock/_class0.py
Main changes:
Changes order of default `sep` to `[';', '&', '?', '#', ',', '~', '.', '-', '_']`
Issues:
-------
Fixes, in devel, issue #170
=> [#170] Fixed order of default separators

datastock/_class1_check.py
Main changes:
* When looking for conflicts, there is now an exception for `'units'`:
- if one dict has units as `str` 
- and the other as `asunits.Unit` 
- but they have the same `str` representation => they are considered equal
Issues:
-------
Fixes, in devel, issue #174
=> `'units'` are equal whether `str` or `asunits.Unit` when looking for conflicts

datastock/_class0.py, datastock/_class1.py, datastock/_saveload.py, datastock/tests/test_01_DataStock.py
Main changes:
* `load(coll=...)` implemented
- unit test implemented
Issues:
-------
Fixes, in devel, issue #184 
Examples:
-----------
=> [#184] Done

datastock/_class1.py, datastock/_class1_color_touch.py, datastock/tests/test_01_DataStock.py
Main changes:
* `get_color_touch(data, dcolor={'a': {'ind': (aa>0.3) & (np.arange(50)[None, :] > 25), 'color': 'r'}})`
Issues:
--------
Fixes, in devel, issue #194 
Examples:
------------
```
coll = ds.DataStock()
aa = np.exp(-(np.arange(50)[:, None]-25)**2/10**2 - (np.arange(50)[None, :]-25)**2/10**2)
dcolor = coll.get_color_touch(aa, dcolor={'foo': {'ind': (aa>0.3) & (np.arange(50)[None, :] > 25), 'color': 'r'}})
dcolor['meaning']
Out[60]: {(1.0, 0.0, 0.0): ['foo']}
```
=> [#194] Operational

datastock/_class2_interactivity.py
Main changes:
* interactivity now used `np.atleast_1d()` to ensure a sequence is passed to `set_xdata()` and `set_ydata()`
Issues:
--------
Fixes, in devel, issue #200
=> [#200] Interactivity fixed for `matplotlib >= 3.9.0`

datastock/_generic_check.py, datastock/tests/test_01_DataStock.py
Main changes:
* `ds._generic_check._check_all_broadcastable(**kwdargs)` implemented
- return `dout, shape`, where `shape` is `None` if all are scalar
- check all provided `kwdargs` are broadcastable against each-other as is (without dimension extension)
Issues:
-------
Fixes, in devel, issue #202
=> Issue202 `_check_all_broadcastable(**kwdargs)`

datastock/_generic_check.py, datastock/tests/test_01_DataStock.py
Main changes:
* `_check_all_broadcastable(return_full_arrays=bool)` implemented
Issues:
--------
Fixes, in devel, issue #204
=> [#204] return_full_arrays=bool implemnented

datastock/_class2.py
Main changes:
* `connect()` now handles an exception specific to python 3.11.11 for matplotlib toolbar initialization that was just triggering a warning without breaking anything => catch and ignore
Issues:
-------
Fixes, in devel, issue #207
=> [#207] Fixed interactivity warning by catching specific Exception

datastock/_class2.py, datastock/_class2_interactivity.py, datastock/_generic_check.py, datastock/tests/test_01_DataStock.py, datastock/version.py, pyproject.toml, scripts/_bash_version.py, scripts/_dparser.py, scripts/main.py, setup.py
Main changes:
* Fixed interactivity with modern `matplotlib` versions
- #208 
* Start using `pyproject.toml` for for availability with uv
- #210
=> Prepare 0.0.48-49

.github/workflows/python-publish.yml, CLASSIFIERS.txt, README.md, datastock/tests/prepublish.py, pyproject.toml
=> [#devel] Prepare 0.0.50

.github/workflows/python-publish-sdist.yml, .github/workflows/python-publish-wheel.yml
Main changes:
* Deployment now achieved via 2 separate actions:
- `sdist` publishing to Pypi
- `wheel` publishing to Pypi on multiple platforms and python versions
Issues:
---------
Fixes, in devel, issue #221
=> [#221] New publishing github actions

.github/workflows/python-publish-sdist.yml, .github/workflows/python-publish-wheel.yml, pyproject.toml
Main changes:
* Deployment improvement
- #222
=> Prepare 0.0.53-54: Deployment improvement
